---
version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=sashank
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jdbc_postgresql_book_relations
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/data/pgadmin

volumes:
  postgres-data:
  pgadmin-data: