services:
  postgres:
    image: postgres:17-bookworm
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jdbc_postgresql_book_relations
#      POSTGRES_DB: jdbc_one_to_one_bi_directional_relations
#      POSTGRES_DB: jdbc_one_to_many_bi_directional_relations
#      POSTGRES_DB: jdbc_many_to_many_bi_directional_relations
      TZ: UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres-data:
    name: postgres-data