server:
  port: 8081

database:
  name: jdbc_one_to_one_bi_directional_relations
  type: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: password

spring:
  application:
    name: one-to-one-bi-directional-relations
  datasource:
    url: jdbc:${database.type}://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
